version: "3.0"
services:
  db:
    build:
      context: '.'
    image: "bozhko-db"
    environment: 
      POSTGRES_USER: "bozhko"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "mydb"
    restart: "unless-stopped"
    ports: 
      - "5432:5432"
  lab2:
    image: "mysql:8.0.26"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
    restart: "unless-stopped"
    ports: 
      - "1234:3306"
